#!/usr/bin/env bash
# ============================================================
#  maxAI — one-command installer
#
#  Installs Docker (if needed), generates all secrets, walks you
#  through a few settings, then builds and starts everything.
#  Designed for a fresh Ubuntu/Debian server, but works on any
#  host with Docker.
# ============================================================
set -euo pipefail

YELLOW='\033[1;33m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; RED='\033[0;31m'; DIM='\033[2m'; NC='\033[0m'
info()  { echo -e "${BLUE}➤${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $1"; }
err()   { echo -e "${RED}✗${NC} $1" >&2; }

cd "$(dirname "$0")"

echo -e "${BLUE}╔══════════════════════════════════════╗${NC}"
echo -e "${BLUE}║            maxAI · installer         ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════╝${NC}\n"

# ── helpers ────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }
is_tty() { [ -t 0 ]; }

SUDO=""
if [ "$(id -u)" -ne 0 ] && have sudo; then SUDO="sudo"; fi

gen_secret() {
  # $1 = number of random bytes
  if have openssl; then openssl rand -hex "$1"; else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

read_env() { [ -f .env ] && grep -E "^$1=" .env 2>/dev/null | head -1 | cut -d= -f2- || true; }

# prompt VAR "Question" "default" [secret]
prompt() {
  local __var="$1" __q="$2" __def="${3:-}" __secret="${4:-}" __input=""
  if ! is_tty; then
    printf -v "$__var" '%s' "$__def"
    return
  fi
  if [ "$__secret" = "secret" ]; then
    read -rs -p "$(echo -e "  ${__q} ${DIM}${__def:+[keep existing]}${NC}: ")" __input; echo
  else
    read -r -p "$(echo -e "  ${__q}${__def:+ ${DIM}[${__def}]${NC}}: ")" __input
  fi
  printf -v "$__var" '%s' "${__input:-$__def}"
}

# ── 1. Docker ──────────────────────────────────────────────
if ! have docker; then
  warn "Docker is not installed."
  if is_tty; then
    read -r -p "  Install Docker now? [Y/n]: " yn; yn=${yn:-Y}
  else yn=Y; fi
  if [[ "$yn" =~ ^[Yy] ]]; then
    info "Installing Docker…"
    curl -fsSL https://get.docker.com | $SUDO sh
    $SUDO systemctl enable --now docker 2>/dev/null || true
  else
    err "Docker is required. Aborting."; exit 1
  fi
fi

# Use sudo for docker if the current user can't reach the daemon.
DOCKER="docker"
if ! docker info >/dev/null 2>&1; then
  if [ -n "$SUDO" ] && $SUDO docker info >/dev/null 2>&1; then
    DOCKER="$SUDO docker"
    warn "Using sudo for Docker. Tip: 'sudo usermod -aG docker \$USER' then re-login to drop sudo."
  else
    err "Cannot talk to the Docker daemon. Is it running?"; exit 1
  fi
fi

if ! $DOCKER compose version >/dev/null 2>&1; then
  err "The Docker Compose plugin was not found. Install it and re-run."; exit 1
fi
ok "Docker is ready"

# ── 2. Secrets (generated once, preserved on re-runs) ──────
POSTGRES_PASSWORD="$(read_env POSTGRES_PASSWORD)"; POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen_secret 24)}"
JWT_SECRET="$(read_env JWT_SECRET)";               JWT_SECRET="${JWT_SECRET:-$(gen_secret 64)}"
ENCRYPTION_KEY="$(read_env ENCRYPTION_KEY)";        ENCRYPTION_KEY="${ENCRYPTION_KEY:-$(gen_secret 32)}"
ok "Secrets generated"

# ── 3. Interactive configuration ───────────────────────────
echo -e "\n${BLUE}Basic settings${NC}"
PORT_DEF="$(read_env PORT)"; PORT_DEF="${PORT_DEF:-80}"
prompt PORT "Port to serve maxAI on" "$PORT_DEF"
URL_DEF="$(read_env FRONTEND_URL)"
if [ -z "$URL_DEF" ]; then
  HOSTIP="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [ "$PORT" = "80" ]; then URL_DEF="http://${HOSTIP:-localhost}"; else URL_DEF="http://${HOSTIP:-localhost}:${PORT}"; fi
fi
prompt FRONTEND_URL "Public URL (how you'll reach the app)" "$URL_DEF"

echo -e "\n${BLUE}Admin account${NC} ${DIM}(only this email can open the admin area)${NC}"
ADMIN_EMAIL_DEF="$(read_env ADMIN_EMAIL)"
prompt ADMIN_EMAIL "Admin email" "$ADMIN_EMAIL_DEF"
ADMIN_PASSWORD="$(read_env ADMIN_PASSWORD)"
if [ -z "$ADMIN_PASSWORD" ]; then
  prompt ADMIN_PASSWORD "Admin password (blank = generate)" "" secret
  if [ -z "$ADMIN_PASSWORD" ]; then ADMIN_PASSWORD="$(gen_secret 9)"; GENERATED_PW=1; fi
fi

echo -e "\n${BLUE}AI provider${NC} ${DIM}(any Chat-Completions-compatible endpoint; leave blank to add later in Settings → Admin)${NC}"
AI_BASE_URL="$(read_env AI_BASE_URL)"
prompt AI_BASE_URL "API base URL" "${AI_BASE_URL:-https://api.openai.com/v1}"
AI_API_KEY="$(read_env AI_API_KEY)"
prompt AI_API_KEY "API key" "$AI_API_KEY" secret
ML="$(read_env AI_MODEL_LITE)";  prompt AI_MODEL_LITE  "Model · Lite"  "${ML:-gpt-4o-mini}"
MP="$(read_env AI_MODEL_PRO)";   prompt AI_MODEL_PRO   "Model · Pro"   "${MP:-gpt-4o}"
MB="$(read_env AI_MODEL_BEAST)"; prompt AI_MODEL_BEAST "Model · Beast" "${MB:-gpt-4o}"

# ── 4. Write .env ──────────────────────────────────────────
info "Writing .env"
umask 077
cat > .env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
POSTGRES_DB=maxai
POSTGRES_USER=maxai
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

NODE_ENV=production
PORT=${PORT}
FRONTEND_URL=${FRONTEND_URL}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=30

# Admin (only this account can open the admin area; created on first boot)
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# AI provider (editable later in Settings → Admin)
AI_BASE_URL=${AI_BASE_URL}
AI_API_KEY=${AI_API_KEY}
AI_MODEL_LITE=${AI_MODEL_LITE}
AI_MODEL_PRO=${AI_MODEL_PRO}
AI_MODEL_BEAST=${AI_MODEL_BEAST}
EOF
ok ".env written"

# ── 5. Build & start ───────────────────────────────────────
info "Building and starting containers (this can take a few minutes)…"
$DOCKER compose up -d --build

echo -e "\n${GREEN}✅ maxAI is running!${NC}"
echo -e "   Open: ${BLUE}${FRONTEND_URL}${NC}"
echo -e "\n   Admin login:"
echo -e "     email:    ${YELLOW}${ADMIN_EMAIL:-<not set>}${NC}"
if [ "${GENERATED_PW:-0}" = "1" ]; then
  echo -e "     password: ${YELLOW}${ADMIN_PASSWORD}${NC}  ${DIM}(auto-generated — save it now)${NC}"
else
  echo -e "     password: ${DIM}(the one you entered)${NC}"
fi
if [ -z "${AI_API_KEY}" ]; then
  echo -e "\n   ${YELLOW}No API key set yet.${NC} Sign in and add it under ${BLUE}Settings → Admin${NC}."
fi
echo -e "\n   ${DIM}Logs:${NC} ${DOCKER} compose logs -f   ${DIM}·${NC}   ${DIM}Stop:${NC} ${DOCKER} compose down   ${DIM}·${NC}   ${DIM}Update:${NC} git pull && ${DOCKER} compose up -d --build"
echo -e "\n   ${DIM}For HTTPS, put maxAI behind a TLS-terminating reverse proxy (see README).${NC}"
